name: Publish to PyPI

on:
  release:
    types: [published] # 创建 Release 时触发
permissions:
  id-token: write # 启用 OIDC
jobs:
  pypi-publish:
    name: Upload release to PyPI
    runs-on: windows-latest
    permissions:
      id-token: write # IMPORTANT: this permission is mandatory for trusted publishing
    steps:
      - uses: actions/checkout@v6

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: false
          package_json_file: "./windows-font-manager-webui/package.json"

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: "latest"
          cache: "pnpm"
          cache-dependency-path: "./windows-font-manager-webui/pnpm-lock.yaml"

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.14"

      - name: Install build dependencies
        run: python -m pip install -U build setuptools

      - name: Build distributions
        run: python run_build.py

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
